package view;

import java.io.File;
import java.sql.*;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class mbarang extends javax.swing.JInternalFrame {
    
    private static Connection koneksi;
    
    public void cleardata() {
        txt_kodebarang.setText(null);
        txt_namabarang.setText(null);
        txt_satuanbarang.setText(null);
        txt_hargabeli.setText(null);
        txt_hargajual.setText(null);
        txt_diskon.setText(null);
    }
    
    private void showdata() {
        dtm = new DefaultTableModel(new String[]{"Kode","Nama","Satuan","Harga Beli","Harga Jual","Diskon"},0);
        Connection koneksi = null;
        Statement sqlCommand = null;
        ResultSet sqlResult = null;
        
        try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
            String dbURL = "jdbc:jtds:sqlserver://localhost:1433/Kasirku;user=admin;password=qwertyx27*";
            koneksi = java.sql.DriverManager.getConnection(dbURL);
            
            sqlCommand = koneksi.createStatement();
            sqlResult = sqlCommand.executeQuery("SELECT * FROM BARANG");
            
            while (sqlResult.next()) {
                String a = sqlResult.getString(1);
                String b = sqlResult.getString(2);
                String c = sqlResult.getString(3);
                String d = sqlResult.getString(4);
                String e = sqlResult.getString(5);
                String f = sqlResult.getString(6);
                dtm.addRow(new Object[] {a,b,c,d,e,f});
                tableBarang.setModel(dtm);
            }
        } catch (Exception e) {
        }
    }
    
     private void disable_txt() {
        txt_kodebarang.requestFocus();
        txt_namabarang.requestFocus();
        txt_satuanbarang.requestFocus();
        txt_hargabeli.requestFocus();
        txt_hargajual.requestFocus();
        txt_diskon.requestFocus();
        
        txt_kodebarang.disable();
        txt_namabarang.disable();
        txt_satuanbarang.disable();
        txt_hargabeli.disable();
        txt_hargajual.disable();
        txt_diskon.disable();
    }
    
    private void enable_txt() {
        txt_kodebarang.requestFocus();
        txt_namabarang.requestFocus();
        txt_satuanbarang.requestFocus();
        txt_hargabeli.requestFocus();
        txt_hargajual.requestFocus();
        txt_diskon.requestFocus();
        
        txt_kodebarang.enable();
        txt_namabarang.enable();
        txt_satuanbarang.enable();
        txt_hargabeli.enable();
        txt_hargajual.enable();
        txt_diskon.enable();
    }

    public mbarang() {
        initComponents();
        showdata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_kodebarang = new javax.swing.JTextField();
        txt_namabarang = new javax.swing.JTextField();
        txt_satuanbarang = new javax.swing.JTextField();
        txt_hargabeli = new javax.swing.JTextField();
        txt_hargajual = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBarang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnReport = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 540));

        jLabel1.setText("Kode");

        jLabel2.setText("Nama");

        jLabel3.setText("Satuan");

        jLabel4.setText("Harga Beli");

        jLabel5.setText("Harga Jual");

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        tableBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Satuan", "Harga Beli", "Harga Jual", "Diskon"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableBarangMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableBarang);

        jLabel6.setText("Diskon");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Master Barang");

        btnReport.setText("Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(22, 22, 22)
                                .addComponent(txt_diskon))
                            .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_hargabeli))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_satuanbarang))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_namabarang)
                                            .addComponent(txt_kodebarang)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_hargajual))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(60, 60, 60)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_kodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_namabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_satuanbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_hargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_hargajual, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(18, 18, 18)
                .addComponent(btnReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Statement sqlCommand = null;
        ResultSet sqlResult = null;
        
        try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
            String dbURL = "jdbc:jtds:sqlserver://localhost:1433/Kasirku;user=admin;password=qwertyx27*";
            koneksi = java.sql.DriverManager.getConnection(dbURL);
            
            String sql = ("INSERT INTO BARANG VALUES ('"+txt_kodebarang.getText()+"','"
                                                        +txt_namabarang.getText()+"','"
                                                        +txt_satuanbarang.getText()+"','"
                                                        +txt_hargabeli.getText()+"','"
                                                        +txt_hargajual.getText()+"','"
                                                        +txt_diskon.getText()+"');");
            
            sqlCommand = koneksi.createStatement();
            sqlResult = sqlCommand.executeQuery(sql);
            
        } catch (Exception se) {
            System.out.println("Error: "+se.getMessage());
        }
        
        cleardata();
        enable_txt();
        showdata();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int option = JOptionPane.showConfirmDialog(null, "Hapus Data Ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (option == JOptionPane.YES_OPTION) {
                Connection koneksi = null;
                Statement sqlCommand = null;
                ResultSet sqlResult = null;
                
                try {
                    Class.forName("net.sourceforge.jtds.jdbc.Driver");
            String dbURL = "jdbc:jtds:sqlserver://localhost:1433/Kasirku;user=admin;password=qwertyx27*";
            koneksi = java.sql.DriverManager.getConnection(dbURL);
            
            sqlCommand = koneksi.createStatement();
            sqlResult = sqlCommand.executeQuery("DELETE FROM BARANG WHERE KODE_BRG='"+txt_kodebarang.getText()+"'");
                } catch (Exception e) {
                }
            }
            cleardata();
            enable_txt();
            showdata();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        cleardata();
        enable_txt();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Connection koneksi = null;
        Statement sqlCommand = null;
        ResultSet sqlResult = null;
        
        try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
            String dbURL = "jdbc:jtds:sqlserver://localhost:1433/Kasirku;user=admin;password=qwertyx27*";
            koneksi = java.sql.DriverManager.getConnection(dbURL);
            
            sqlCommand = koneksi.createStatement();
            sqlResult = sqlCommand.executeQuery("UPDATE BARANG SET nama_brg='"+txt_namabarang.getText()+
                    "', satuan_brg='"+txt_satuanbarang.getText()+
                    "', hrg_beli='"+txt_hargabeli+
                    "', hrg_jual='"+txt_hargajual.getText()+
                    "', diskon='"+txt_diskon.getText()+
                    " where kode_brg='"+txt_kodebarang.getText()+"';");
        } catch (Exception e) {
        }
        
        cleardata();
        enable_txt();
        showdata();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        showdata();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tableBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBarangMousePressed
         if (evt.getClickCount() == 1) { 
               enable_txt();
               txt_kodebarang.disable();
               txt_namabarang.requestFocus();
               JTable target = (JTable)evt.getSource();
               int row = target.getSelectedRow();
               //int column = target.getSelectedColumn();
               //JOptionPane.showMessageDialog(null, tblBarang.getValueAt(row, column)); // get the value of a row and column.
               txt_kodebarang.setText((String) tableBarang.getValueAt(row, 0));
               txt_namabarang.setText((String) tableBarang.getValueAt(row, 1));
               txt_satuanbarang.setText((String) tableBarang.getValueAt(row, 2));
               txt_hargabeli.setText((String) tableBarang.getValueAt(row, 3));
               txt_hargajual.setText((String) tableBarang.getValueAt(row, 4));
               txt_diskon.setText((String) tableBarang.getValueAt(row, 5));
            }
    }//GEN-LAST:event_tableBarangMousePressed

    JasperReport jr;
    Map param = new HashMap();
    JasperPrint jp;
    JasperDesign jd;
    
    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        try { 
            manggil();
            
            File report = new File("D:\\Drive\\Documents\\Dinamika\\SEM 3\\Pemrograman Basis Data (P1)\\NetBeans\\Kasirku\\src\\view\\reportPenjualan.jrxml");
            jd = JRXmlLoader.load(report);
            param.clear();
            jr = JasperCompileManager.compileReport(jd);
            jp = JasperFillManager.fillReport(jr, param, getConnection());
            JasperViewer.viewReport(jp, isClosed);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_btnReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBarang;
    private javax.swing.JTextField txt_diskon;
    private javax.swing.JTextField txt_hargabeli;
    private javax.swing.JTextField txt_hargajual;
    private javax.swing.JTextField txt_kodebarang;
    private javax.swing.JTextField txt_namabarang;
    private javax.swing.JTextField txt_satuanbarang;
    // End of variables declaration//GEN-END:variables
    
    //Master Barang
    DefaultTableModel dtm;
    
    String KB;
    String NB;
    String ST;
    int HB = 0;
    int HJ = 0;
    
    public static Connection getConnection() throws Exception {
        try {
            String dbURL = "jdbc:sqlserver://localhost;database=Kasirku;user=admin;password=qwertyx27*";
            koneksi = DriverManager.getConnection(dbURL);
        } catch (Exception se) {
            System.out.println("Error: "+se.getMessage());
        }
        return koneksi;
    }
    
    public static void manggil() throws SQLException {
            try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
            String dbURL = "jdbc:jtds:sqlserver://localhost:1433/Kasirku;user=admin;password=qwertyx27*";
            koneksi = java.sql.DriverManager.getConnection(dbURL);
        } catch (Exception e) {
        }
    }
}

